/** @type {import('next').NextConfig} */
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

const nextConfig = {
  reactStrictMode: true,
  basePath,
  async redirects() {
    return [
      { source: '/blogs', destination: '/blog', permanent: true },
      { source: '/book-hotel', destination: '/hotels', permanent: true },
      { source: '/book-flights', destination: '/flights', permanent: true },
      { source: '/blogs/:path*', destination: '/blog/:path*', permanent: true },
      { source: "/book-hotel/denmark", destination: "/hotels-in-denmark", permanent: true },
      { source: "/book-hotel/glasgow", destination: "/hotels-in-glasgow", permanent: true },
      { source: "/book-hotel/goa", destination: "/hotels-in-goa", permanent: true },
      { source: "/book-hotel/new-york", destination: "/hotels-in-new-york", permanent: true },
      { source: "/book-hotel/ireland", destination: "/hotels-in-ireland", permanent: true },
      { source: "/book-hotel/manchester", destination: "/hotels-in-manchester", permanent: true },
      { source: "/book-hotel/paris", destination: "/hotels-in-paris", permanent: true },
      { source: "/book-hotel/san-francisco", destination: "/hotels-in-san-francisco", permanent: true },
      { source: "/book-hotel/new-york", destination: "/hotels-in-new-york", permanent: true },
      { source: "/book-hotel/san-francisco", destination: "/hotels-in-san-francisco", permanent: true },
      { source: "/dubai", destination: "/hotels-in-dubai", permanent: true },
      { source: "/tokyo", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/singapore", destination: "/hotels-in-singapore", permanent: true },
      { source: "/newyork", destination: "/hotels-in-new-york", permanent: true },
      { source: "/goa", destination: "/hotels-in-goa", permanent: true },
      { source: "/canada", destination: "/hotels-in-canada", permanent: true },
      { source: "/australia", destination: "/hotels-in-australia", permanent: true },
      { source: "/denmark", destination: "/hotels-in-denmark", permanent: true },
      { source: "/ireland", destination: "/hotels-in-ireland", permanent: true },
      { source: "/united-kingdom", destination: "/hotels-in-uk", permanent: true },
      { source: "/manchester", destination: "/hotels-in-manchester", permanent: true },
      { source: "/glasgow", destination: "/hotels-in-glasgow", permanent: true },
      { source: "/san-francisco", destination: "/hotels-in-san-francisco", permanent: true },
      { source: "/book-hotel/new-york-2", destination: "/hotels-in-new-york", permanent: true },
      { source: "/book-hotel/singapore", destination: "/hotels-in-singapore", permanent: true },
      { source: "/book-hotel/dubai", destination: "/hotels-in-dubai", permanent: true },
      { source: "/book-hotel/tokyo", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/denmark", destination: "/hotels-in-denmark", permanent: true },
      { source: "/book-hotel/united-kingdom", destination: "/hotels-in-uk", permanent: true },
      { source: "/book-hotel/ireland", destination: "/hotels-in-ireland", permanent: true },
      { source: "/book-hotel/glasgow", destination: "/hotels-in-glasgow", permanent: true },
      { source: "/book-hotel/manchester", destination: "/hotels-in-manchester", permanent: true },
      { source: "/book-hotel/paris", destination: "/hotels-in-paris", permanent: true },
      { source: "/book-hotel/usa", destination: "/hotels-in-usa", permanent: true },
      { source: "/book-hotel/new-york", destination: "/hotels-in-new-york", permanent: true },
      { source: "/book-hotel/san-francisco", destination: "/hotels-in-san-francisco", permanent: true },
      { source: "/book-hotel/canada", destination: "/hotels-in-canada", permanent: true },
      { source: "/book-hotel/australia", destination: "/hotels-in-australia", permanent: true },
      { source: "/book-hotel/sydney", destination: "/hotels-in-sydney", permanent: true },
      { source: "/book-hotel/london", destination: "/hotels-in-london", permanent: true },
      { source: "/about", destination: "/about-us", permanent: true },
      { source: "/book-hotel/usa", destination: "/hotels-in-usa", permanent: true },
      { source: "/book-hotel/manchester/page/1", destination: "/hotels-in-manchester", permanent: true },
      { source: "/book-hotel/london/page/1", destination: "/hotels-in-uk", permanent: true },
      { source: "/book-hotels-online/hotels-in-dubai", destination: "/hotels-in-dubai", permanent: true },
      { source: "/book-hotel/glasgow/page/1", destination: "/hotels-in-glasgow", permanent: true },
      { source: "/book-hotel/singapore/page/1", destination: "/hotels-in-singapore", permanent: true },

      { source: "/book-hotel/glasgow/page/30", destination: "/hotels-in-glasgow", permanent: true },
      { source: "/book-flights-/london/page/25", destination: "/flights", permanent: true },
      { source: "/book-flights/london/page/16", destination: "/flights", permanent: true },
      { source: "/book-flights-/london/page/2", destination: "/flights", permanent: true },


      // { source: "/?blog_post_page=38", destination: "/blog", permanent: true },
      { source: "/book-hotel/glasgow/page/43", destination: "/hotels-in-glasgow", permanent: true },
      { source: "/book-hotel/contact/page/35", destination: "/contact-us", permanent: true },
      { source: "/book-flights-/london/page/41", destination: "/flights", permanent: true },

      { source: "/book-flights/new-york-to-london", destination: "/flights", permanent: true },
      { source: "/top-travel-packages", destination: "/book-packages", permanent: true },


      // { source: "/?blog_post_page=1", destination: "/blog", permanent: true },
      { source: "/exclusive-luxury-hotel-deals-discounts-find-with-justbuytravel-today", destination: "/hotels", permanent: true },
      { source: "/why-dubai-should-be-your-next-destination-how-to-find-cheap-flights-online", destination: "/flights", permanent: true },

      { source: "/2025/06/16", destination: "/", permanent: true },
      { source: "/contact/page/44", destination: "/contact-us", permanent: true },
      { source: "/book-flights/london/page/22", destination: "/flights", permanent: true },
      { source: "/book-flights/new-york", destination: "/flights", permanent: true },
      { source: "/book-hotel/new-york/page/2", destination: "/hotels-in-new-york", permanent: true },
      { source: "/book-hotel/liverpool", destination: "/hotels", permanent: true },
      { source: "/contact/page/26", destination: "/contact-us", permanent: true },
      { source: "/contact/page/22", destination: "/contact-us", permanent: true },
      { source: "/book-flights/paris/page/29", destination: "/flights", permanent: true },
      { source: "/book-flights/paris/page/30", destination: "/flights", permanent: true },
      { source: "/book-flights/paris/page/27", destination: "/flights", permanent: true },
      { source: "/book-hotel/tokyo/page/10", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/tokyo/page/28", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/tokyo/page/32", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/tokyo/page/29/", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/tokyo/page/24", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/tokyo/page/13", destination: "/hotels-in-tokyo", permanent: true },


      { source: "/book-hotel/tokyo/page/30", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-hotel/tokyo/page/11", destination: "/hotels-in-tokyo", permanent: true },
      { source: "/book-flights/dubai/page/27", destination: "/flights", permanent: true },
      { source: "/book-flights/dubai/page/26", destination: "/flights", permanent: true },
      { source: "/book-flights/paris/page/42", destination: "/flights", permanent: true },
      { source: "/book-flights/paris/page/39", destination: "/flights", permanent: true },
      { source: "/contact/page/35", destination: "/contact-us", permanent: true },
      { source: "/contact/page/39", destination: "/contact-us", permanent: true },
      { source: "/book-flights/paris/page/4", destination: "/flights", permanent: true },
      { source: "/contact/page/2", destination: "/contact-us", permanent: true },


      // { source: "/?blog_post_page=2", destination: "/blog", permanent: true },
      {
        source: '/',
        has: [{ type: 'query', key: 'blog_post_page' }],
        destination: '/blog',
        permanent: true,
      },
      { source: "/book-flights/paris/page/6", destination: "/flights", permanent: true },
      { source: "/book-flights/paris/page/3", destination: "/flights", permanent: true },
      { source: "/contact/page/42", destination: "/contact-us", permanent: true },
      { source: "/contact/page/6", destination: "/contact-us", permanent: true },
      { source: "/cdn-cgi/l/email-protection", destination: "/", permanent: true },
      { source: "/book-hotels-online", destination: "/hotels", permanent: true },




    ];
  },
}
export default nextConfig;
